name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Run golangci-lint
        run: |
          eval "$(mise activate bash)"
          mise run lint
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Run tests
        run: |
          eval "$(mise activate bash)"
          mise run test-verbose
        
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Build for all platforms
        run: |
          eval "$(mise activate bash)"
          mise run build-all

  binary-test:
    name: Binary Command Tests
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Build binary
        run: |
          eval "$(mise activate bash)"
          mise run build
          
      - name: Test binary version
        run: |
          ./bin/server --version
          
      - name: Test binary help
        run: |
          ./bin/server --help
          
      - name: Test binary with invalid flag
        run: |
          # Test that binary exits with error code when given invalid flag
          if ./bin/server --invalid-flag 2>/dev/null; then
            echo "ERROR: Binary should have failed with invalid flag"
            exit 1
          else
            echo "SUCCESS: Binary correctly rejected invalid flag"
          fi
          
      - name: Test binary with custom configuration
        run: |
          # Test that binary accepts all expected flags without errors
          timeout 2s ./bin/server --host http://localhost:11434 --context-size 4096 --code-model codellama:7b --chat-model llama2:7b --keep-alive 5m || true
          
      - name: List available commands
        run: |
          echo "=== Available Command-Line Flags ==="
          ./bin/server --help 2>&1 | grep -E "^\s+-" || true
          echo ""
          echo "=== MCP Tools Provided by Server ==="
          echo "1. chat - Chat with configured model"
          echo "2. code - Generate code with configured model"
          echo "3. list-models - List available Ollama models"
          echo "4. model-info - Get model information"
          echo "5. pull-model - Pull model from Ollama library"
