name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Run golangci-lint
        run: |
          eval "$(mise activate bash)"
          mise run lint
        
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Run tests
        run: |
          eval "$(mise activate bash)"
          mise run test-verbose
        
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mise
        run: |
          curl https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          
      - name: Install tools with mise
        run: |
          mise install
          eval "$(mise activate bash)"
          
      - name: Build for all platforms
        run: |
          eval "$(mise activate bash)"
          mise run build-all
